str1="My name is Anurag"
print(str1)
l=len(str1)
print("The length of the string",l)
s=str1.upper()
print("Uppercase:",s)
a=str1.lower()
print("Lowercase:", a)
m=str1.split()
print("After Splitting:", m)
n=str1.split('a')
print("Splitting using a as an operator:", n)
print(str1[2:5])
print(str1[1:5])
print(str1[3:5])
print(str1[4:7])
print(str1[6:8:4])
print(str1[1:5:2])
print(str1[1:11:1])
print(str1[1:9:5])
print(str1[1:7:5])
print(str1[1:5:3])
print(str1[::-1])